### ISSUE TITLE
Rename to VBA-Require

### ISSUE THREAD

**Issue by connerk** [richardtallent/VBA-Require#1]
Man, I've been wanting to do this work for some time!

Any chance at renaming it to VBA-Require in compliance with 
[VBA Tools](https://github.com/VBA-tools) standard? 

that dude has made some awesome stuff that I see you have used. it would be nice to lump all the awesome VBA stuff together since high quality FLOSS VBA modules are hard to come by.

**Comment by richardtallent** [comment]
Thanks Kevin!

I agree, VBA-Require makes more sense, and better to fix it now than later.

I've also massively updated the README, based on looking into this off and on over the past few months. The original concept of self-updating tools is too rife with potential problems, but a great tool for updating macro modules (hosted anywhere) I believe is very possible.
